### ISSUE TITLE
No data in Response (nach ca 1h)

### ISSUE THREAD

**Issue by marlan99** [TA2k/ioBroker.bwt#3]
Mit der aktuellen Version (09.02.2022) gibt es folgendes Problem:

Die Fehler tauchen immer nach ca 1h nach starten der Instanz auf.
Meine Konfiguration ist:
Lokale Abfrage: 60 sek.
Cloud Abfrage: 2 min.

`

0 | 2022-01-09 18:14:24.424 | info | {"Meta":{"Code":"14","RequestId":"ed398125-773e-4d8b-b286-4188c0699dc2","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
-- | -- | -- | --
bwt.0 | 2022-01-09 18:14:24.424 | error | No Data in response
bwt.0 | 2022-01-09 18:14:24.423 | debug | {"Meta":{"Code":"14","RequestId":"ed398125-773e-4d8b-b286-4188c0699dc2","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:24.166 | info | {"Meta":{"Code":"14","RequestId":"69ebf8f3-f4b7-46ad-9de3-1e41d4010d82","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:24.165 | error | No Data in response
bwt.0 | 2022-01-09 18:14:24.165 | debug | {"Meta":{"Code":"14","RequestId":"69ebf8f3-f4b7-46ad-9de3-1e41d4010d82","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.873 | info | {"Meta":{"Code":"14","RequestId":"809f4b81-48d8-41ea-8bd1-81f5c580cae0","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.872 | error | No Data in response
bwt.0 | 2022-01-09 18:14:23.871 | debug | {"Meta":{"Code":"14","RequestId":"809f4b81-48d8-41ea-8bd1-81f5c580cae0","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.856 | debug | Cannot extract empty: dc775c8a-88f8-4ca8-bac7-a0de22ee61b2.notifications
bwt.0 | 2022-01-09 18:14:23.855 | debug | {"Meta":{"Code":"14","RequestId":"ed20c113-2418-487a-b2a0-48abdbac73ba","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.848 | debug | Cannot extract empty: dc775c8a-88f8-4ca8-bac7-a0de22ee61b2.waterconsumption
bwt.0 | 2022-01-09 18:14:23.847 | debug | {"Meta":{"Code":"14","RequestId":"45577930-af0f-4ea5-8e2f-1c774bcfd799","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.845 | debug | Cannot extract empty: dc775c8a-88f8-4ca8-bac7-a0de22ee61b2.telemetry
bwt.0 | 2022-01-09 18:14:23.844 | debug | {"Meta":{"Code":"14","RequestId":"69e3a05d-c129-4c0c-847e-6d4a51aad5c7","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.839 | debug | Cannot extract empty: dc775c8a-88f8-4ca8-bac7-a0de22ee61b2.saltConsumption
bwt.0 | 2022-01-09 18:14:23.838 | debug | {"Meta":{"Code":"14","RequestId":"8bb2359c-dc80-45c2-9eeb-8b0a915fe611","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.818 | debug | Cannot extract empty: dc775c8a-88f8-4ca8-bac7-a0de22ee61b2.limeFiltered
bwt.0 | 2022-01-09 18:14:23.817 | debug | {"Meta":{"Code":"14","RequestId":"e6b04d93-c68d-4527-a4bd-47338fba0a9f","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:14:23.500 | debug | https://api.bwt-group.com/api/perla/dc775c8a-88f8-4ca8-bac7-a0de22ee61b2/saltConsumption?from=2021-10-01&aggregation=day&to=2022-01-09
bwt.0 | 2022-01-09 18:14:23.498 | debug | https://api.bwt-group.com/api/device/dc775c8a-88f8-4ca8-bac7-a0de22ee61b2/waterconsumption/daily?since=2021-10-01&until=2022-01-09
bwt.0 | 2022-01-09 18:14:23.496 | debug | https://api.bwt-group.com/api/mobilebackend/dc775c8a-88f8-4ca8-bac7-a0de22ee61b2/limeFiltered
bwt.0 | 2022-01-09 18:14:23.494 | debug | https://api.bwt-group.com/api/device/dc775c8a-88f8-4ca8-bac7-a0de22ee61b2/notifications?orderAsc=true
bwt.0 | 2022-01-09 18:14:23.491 | debug | https://api.bwt-group.com/api/perla/dc775c8a-88f8-4ca8-bac7-a0de22ee61b2/telemetry
bwt.0 | 2022-01-09 18:14:21.362 | debug | {"aktuellerDurchfluss":"0","aktuellerDurchflussProzent":"0","durchflussHeute":"123","durchflussMonat":"3033","durchflussJahr":"30","RegeneriemittelNachfuellenIn":"98","RegeneriemittelVerbleibend":"100"}
bwt.0 | 2022-01-09 18:14:21.342 | debug | {"aktuell":"0"}
bwt.0 | 2022-01-09 18:13:21.128 | debug | {"aktuellerDurchfluss":"0","aktuellerDurchflussProzent":"0","durchflussHeute":"123","durchflussMonat":"3033","durchflussJahr":"30","RegeneriemittelNachfuellenIn":"98","RegeneriemittelVerbleibend":"100"}
bwt.0 | 2022-01-09 18:13:21.109 | debug | {"aktuell":"0"}
bwt.0 | 2022-01-09 18:12:24.374 | info | {"Meta":{"Code":"14","RequestId":"7a36929c-6b3e-4dc2-b112-04eb88b3b756","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 18:12:24.373 | error | No Data in response

`

**Comment by TA2k** [comment]
Installier mal neu aber nach exakt 60min müsste sich ein neuen token holen, bitte mal schauen ob das passiert

**Comment by marlan99** [comment]
Update gemacht um 19:39 die Instanz gestartet und seit 20:39 wieder die Fehlermeldungen drin.
Kann Zufall sein, aber vor der Anpassung der Lösung von issue#2 hatte ich diese Meldungen nicht.

`

bwt.0 | 2022-01-09 20:39:34.819 | error | No Data in response
-- | -- | -- | --
bwt.0 | 2022-01-09 20:39:34.559 | info | {"Meta":{"Code":"14","RequestId":"665b9a22-8b18-4456-8778-6eda3192772f","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-09 20:39:34.558 | error | No Data in response
bwt.0 | 2022-01-09 20:39:33.337 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:39:33.286 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:39:30.591 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:29:33.660 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:29:33.091 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:29:30.591 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:19:30.591 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:09:32.745 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 20:09:30.589 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 19:59:32.744 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 19:59:30.588 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 19:49:30.588 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-09 19:39:34.144 | info | Found 1 devices
bwt.0 | 2022-01-09 19:39:32.677 | info | Login to App succesfull
bwt.0 | 2022-01-09 19:39:30.588 | info | Login to App

`

**Comment by TA2k** [comment]
Debug log wäre noch wichtig

**Comment by TA2k** [comment]
Bitte nochmal neu installieren

**Comment by marlan99** [comment]
neu installiert heute um 09:44 und dieselben Fehler noch da.
Habe leider vergessen auf debug zu stellen. Habe dies nun gemacht und liefere die logs noch nach:

woran sehe ich, dass das update jeweils auch deine aktuellste Version ist?
Beim Adapter wird leider immer 0.0.1 angezeigt.

`

bwt.0 | 2022-01-10 10:44:40.436 | info | {"Meta":{"Code":"14","RequestId":"9f7e6c74-9726-4191-bdff-579ae8267e3d","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
-- | -- | -- | --
bwt.0 | 2022-01-10 10:44:40.436 | error | No Data in response
bwt.0 | 2022-01-10 10:44:40.190 | info | {"Meta":{"Code":"14","RequestId":"43fc8d27-896b-4cc8-b7cb-4a78cb226507","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-10 10:44:40.190 | error | No Data in response
bwt.0 | 2022-01-10 10:44:39.506 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:44:39.489 | info | local login https://192.168.1.125/users/login

`

**Comment by marlan99** [comment]
Ergänzung:

Die Fehlermeldung kommt jetzt nur einmal und danach scheint die Verbindung wieder zu funktionieren.
Evtl. noch ein kleines Timing Problem hier ?

`

bwt.0 | 2022-01-10 10:54:39.258 | info | local login https://192.168.1.125/users/login
-- | -- | -- | --
bwt.0 | 2022-01-10 10:54:36.758 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:44:40.436 | info | {"Meta":{"Code":"14","RequestId":"9f7e6c74-9726-4191-bdff-579ae8267e3d","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-10 10:44:40.436 | error | No Data in response
bwt.0 | 2022-01-10 10:44:40.190 | info | {"Meta":{"Code":"14","RequestId":"43fc8d27-896b-4cc8-b7cb-4a78cb226507","Message":"The applikation is not allowed to access this service. code: (14)","Details":null,"OriginalErrorMessage":"The application is not allowed to access this service.","StatusCode":500,"Type":"ErrorMessage"}}
bwt.0 | 2022-01-10 10:44:40.190 | error | No Data in response
bwt.0 | 2022-01-10 10:44:39.506 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:44:39.489 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:44:36.758 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:34:39.768 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:34:39.247 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:34:36.758 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:24:39.250 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:24:36.757 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:14:39.770 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:14:39.221 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:14:36.757 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:04:39.877 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:04:39.311 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 10:04:36.757 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 09:54:39.121 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 09:54:36.757 | info | local login https://192.168.1.125/users/login
javascript.0 | 2022-01-10 09:51:07.399 | info | Stop script script.js.Chromecast_Steuerungen.Büro_Musik_Nicole_-_OldiesButGoldies
javascript.0 | 2022-01-10 09:51:07.380 | info | script.js.Chromecast_Steuerungen.Büro_Musik_Nicole_-_OldiesButGoldies: registered 0 subscriptions and 0 schedules
javascript.0 | 2022-01-10 09:51:07.370 | info | Start javascript script.js.Chromecast_Steuerungen.Büro_Musik_Nicole_-_OldiesButGoldies
bwt.0 | 2022-01-10 09:44:39.773 | info | Found 1 devices
bwt.0 | 2022-01-10 09:44:38.328 | info | Login to App succesfull
bwt.0 | 2022-01-10 09:44:36.757 | info | Login to App

`

**Comment by TA2k** [comment]
ich habe nochmal die refresh token zeit ein wenig verkürzt

**Comment by marlan99** [comment]
update gerade nochmal durchgeführt und beobachte weiter, aber sieht schon sehr gut aus :-)

Könnte man diese Meldungen anstelle "info" als "debug" Meldungen ausgeben lassen?



bwt.0 | 2022-01-10 11:34:39.905 | info | local login https://192.168.1.125/users/login
-- | -- | -- | --
bwt.0 | 2022-01-10 11:34:39.334 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 11:34:36.762 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 11:24:39.256 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 11:24:36.762 | info | local login https://192.168.1.125/users/login
bwt.0 | 2022-01-10 11:14:39.795 | info | local login https://192.168.1.125/users/login

**Comment by TA2k** [comment]
habe ich eigentlich gemacht nochmal installieren?

**Comment by marlan99** [comment]
Habs grad gesehen. Mit der letzten Änderung ist bis jetzt alles ok.
Läuft seit 11:56:00 Uhr und hat keine Fehlermeldungen mehr drin.

Auch die obige info Meldung erscheint nicht mehr als info.

DANKE

**Comment by marlan99** [comment]
Nach nun 20h Dauerbetrieb keine token Probleme mehr vorhanden.
Einzige Fehlermeldung war die folgende von heute morgen, wobei dies meiner Ansicht nach nichts mit diesem issue hier zu tun hat. Daher schliesse ich dieses issue.

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
bwt.0 | 2022-01-11 06:21:13.603 | error | Error: read ECONNRESET
