### ISSUE TITLE
Manche Daten werden nicht aktualisiert

### ISSUE THREAD

**Issue by mbhomie007** [TA2k/ioBroker.bwt#4]
Manche Daten werden nicht aktualisiert.

Lokale Abfrage über IP-Addresse und einem Intervall von 60 Sekunden sind eingestellt.

![image](https://user-images.githubusercontent.com/64688879/152691357-58012da0-c95f-4c02-bb1d-1e9c5c8af1da.png)

Letzte Regeneration wurde gestern gemacht und nicht wie angezeigt am 27./28.01.

![image](https://user-images.githubusercontent.com/64688879/152691252-75f544ac-bd7a-4c65-814b-9bd79ac351bb.png)

Andere Daten werden im eingestellten Intervall korrekt abgefragt.
Ein Neustart des Adapters brachte keine Besserung.

**Comment by mbhomie007** [comment]
Zusatz: 
Die Nicht-Aktualisierung kommt auch noch bei vielen anderen Daten vor.
"Letzte Regeneration" , oben gezeigt, ist nur ein Beispiel.

"Aktueller Durchfluss" hingegen wird korrekt aktualisiert.

**Comment by TA2k** [comment]
Ordner telemetry löschen und adapter neustarten werden die datenpunkte angelegt?

**Comment by mbhomie007** [comment]
Ich habe den Ordner "telemetry" gelöscht und den Adapter neu gestartet.
Der Ordner "telemetry" wurde nicht neu angelegt...

Habe mir alle Ordner nochmal angeschaut, alle Daten sind veraltet vom 29.01 , da wurde der Adapter installiert.

Lediglich der Ordner "actualizedata" wird im eingestellten Intervall aktualisiert.

Der Log zeigt keine auffälligen Einträge.

**Comment by mbhomie007** [comment]
Hast du noch eine Idee, woran es liegen kann?

**Comment by TA2k** [comment]
Keine Ahnung müsste man im debug mode schauen ob er sich korrekt mit cloud verbindet oder nur lokal

**Comment by mbhomie007** [comment]
Habe nun auch die Cloud-Anmeldedaten (BWT-App) eingegeben, nun funktioniert auch die Aktualisierung aller Daten im eingestellten Intervall.

Also nur die lokale Abfrage per IP-Adresse funktioniert leider nicht.
Im debug mode Log waren keine Fehler zu sehen.
Schade, ich wollte eigentlich nur die lokale Abfrage machen...

Vielleicht bekommt man dies zukünftig mit einem Update irgendwie hin.

**Comment by mbhomie007** [comment]
Habe dazu mal ein neues Ticket aufgemacht. 
#8
