### ISSUE TITLE
Fehler mit js-controller 4.0

### ISSUE THREAD

**Issue by mbhomie007** [TA2k/ioBroker.bwt#7]
**node: v14.19.0, js-controller: 4.0.10**

<html>
<body>

bwt.0 | 2022-02-18 15:43:31.374 | info | State value to set for "bwt.0.XXXXXXXXXXXXXXXX.general.DeviceParameter.0" has to be type "string" but received type "number"
-- | -- | -- | --
bwt.0 | 2022-02-18 15:43:28.185 | warn | Object of state "bwt.0.actualizedata" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:43:28.182 | warn | Object of state "bwt.0.wasserverbrauch" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:42:28.499 | warn | Object of state "bwt.0.actualizedata" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:42:28.466 | warn | Object of state "bwt.0.wasserverbrauch" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:41:28.207 | warn | Object of state "bwt.0.actualizedata" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:41:28.194 | warn | Object of state "bwt.0.wasserverbrauch" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:40:28.180 | warn | Object of state "bwt.0.actualizedata" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:40:28.161 | warn | Object of state "bwt.0.wasserverbrauch" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:39:28.201 | warn | Object of state "bwt.0.actualizedata" is missing the required property "common.type"
bwt.0 | 2022-02-18 15:39:28.177 | warn | Object of state "bwt.0.wasserverbrauch" is missing the required property "common.type"

</body>
</html>

**Comment by mbhomie007** [comment]
Nach löschen der Ordner und Neustart des Adapters werden die Ordner "Wasserverbrauch" und "actualizedata" nicht mehr richtig angezeigt...

![image](https://user-images.githubusercontent.com/64688879/154723320-6ba42d4b-8c69-4032-921f-107b582cef37.png)

**Comment by TA2k** [comment]
Der Fehler wird in der github version ordentlich behandelt

**Comment by mbhomie007** [comment]
![image](https://user-images.githubusercontent.com/64688879/154969675-cf999707-5889-4e5b-8196-8219928861af.png)

Nach dem Adapter-Update auf 0.0.4 werden die Ordner "Wasserverbrauch" und "actualizedata" nicht mehr erzeugt.

![image](https://user-images.githubusercontent.com/64688879/154969502-2979b3dc-1b67-49b0-a979-74a2a63ab25c.png)

Wenn ich die lokalen Einstellungen im Adapter lösche, also nur die Cloud (BWT-App) Daten eingetragen sind, sind die Warnungen im Log weg.
Die Ordner "Wasserverbrauch" und "actualizedata" werden aber **trotzdem** nicht mehr neu erstellt.

**Comment by TA2k** [comment]
Anscheinend kann er sich lokal nicht einloggen nochmal die zugangsdaten überprüfen ob das soweit passt

**Comment by TA2k** [comment]
Nein ist kein Problem die beiden ordner werden aus lokalen daten bezogen wenn der lokale weg nicht geht dann gibt es dir ordner nicht

**Comment by mbhomie007** [comment]
> ![image](https://user-images.githubusercontent.com/64688879/154969675-cf999707-5889-4e5b-8196-8219928861af.png)
> 
> Nach dem Adapter-Update auf 0.0.4 werden die Ordner "Wasserverbrauch" und "actualizedata" nicht mehr erzeugt.
> 

Dann ist dies der aktuelle Stand. 
Dann habe ich dort ja keinen Fehler gemacht.

Die Ordner werden nicht mehr angelegt. 

Mit der Adapter Version 0.0.3 und js controller V3 funktionierte alles, mit der Lokalen Abfrage und auch die Cloud Abfrage.

**Comment by mbhomie007** [comment]
Vielleicht mit den Fehlern oben zu tun, die mit js controller V4 aufkamen:

bwt.0	2022-02-18 15:42:28.499	warn	Object of state "bwt.0.actualizedata" is missing the required property "common.type"

bwt.0	2022-02-18 15:42:28.466	warn	Object of state "bwt.0.wasserverbrauch" is missing the required property "common.type"

**Comment by TA2k** [comment]
Es wurde an der lokale Abfrage nichts geändert.
Der jscontroller hat damit auch nichts zu tun der Fehler kam nur weil versucht wurde die Fehlermeldung von der lokalen Schnittstelle als State zu schreiben

Du kannst den Adapter in debug log level setzen und dann siehst du was die lokale Schnittstelle für eine Fehler HTML seite zurückgibt

**Comment by mbhomie007** [comment]
> Es wurde an der lokale Abfrage nichts geändert.
> Der jscontroller hat damit auch nichts zu tun der Fehler kam nur weil versucht wurde die Fehlermeldung von der lokalen Schnittstelle als State zu schreiben

Komisch, aber vorher funktionierte ja alles mit lokaler Abfrage und auch per Cloud Abfrage... 
Sonst habe ich nichts geändert. 

> Du kannst den Adapter in debug log level setzen und dann siehst du was die lokale Schnittstelle für eine Fehler HTML seite zurückgibt

Sorry! Ich habe doch oben, siehe Screenshot, die Adapter Ausgabe auf debug stehen. Kannst du das genauer erklären?

**Comment by TA2k** [comment]
dann schick mit die log datei per mail tombox2020@gmail.com

**Comment by mbhomie007** [comment]
Im Log sind leider auch nur die Einträge wie oben im Screenshot zu sehen.

![image](https://user-images.githubusercontent.com/64688879/155346858-b940a987-0871-4d9d-ac55-0b945ded3ad6.png)

**Comment by TA2k** [comment]
im log level debug sollte mehr zu sehen sein

**Comment by mbhomie007** [comment]
Es sollte alles geloggt werden.

![image](https://user-images.githubusercontent.com/64688879/155733541-4c2a10a2-5106-4f99-89c2-969f41e9d14e.png)

![image](https://user-images.githubusercontent.com/64688879/155734307-9f041909-d5ae-450f-ae55-52c5f960b342.png)

Sorry! Ich weiß da nichts anderes einzustellen,  steht auf debug.

**Comment by mbhomie007** [comment]
@TA2k 
Hast du noch eine Idee was man versuchen kann?
"local data" wird leider überhaupt nicht mehr ausgelesen...

**Comment by mbhomie007** [comment]
Weiter gehts hier: #8
