### ISSUE TITLE
Lokale Abfrage per IP-Adresse nicht möglich

### ISSUE THREAD

**Issue by mbhomie007** [TA2k/ioBroker.bwt#8]
![image](https://user-images.githubusercontent.com/64688879/159926773-2b323326-2a50-48db-8953-1fbd5e835110.png)

Die Daten/Ordner "Wasserverbrauch" und "actualizedata" werden nicht mehr abgefragt/angezeigt...

Die Adapter Einstellungen wurden kontrolliert, das Passwort stimmt.

![image](https://user-images.githubusercontent.com/64688879/159927024-47d61d2a-0760-406a-b416-b690f5a1726f.png)

Über meine Benutzeroberfläche der FritzBox 7590 komme ich über den den Browser auf die Anlage per WEB-Zugriff.
Adresse:
http://192.168.178.116:6080/vnc.html?resize=scale&autoconnect=true&show_dot=true
Der Login funktioniert mit dem Passwort, das auch in den Adaptereinstellungen oben hinterlegt ist, einwandfrei.

![image](https://user-images.githubusercontent.com/64688879/159927394-8aef40ab-f4dd-45f8-b7fd-74638cddaf9c.png)

Die Abfrage per App hingegen funktioniert sehr gut.

**Comment by mbhomie007** [comment]
Also ist eine lokale Abfrage überhaupt nicht mehr möglich?

**Comment by TA2k** [comment]
Nicht mit der VNC firmware

**Comment by mbhomie007** [comment]
Sorry...
Kann man dies in einer neuen Adapter-Version eventuell integrieren?
Oder gibt es Umwege, dies trotzdem irgendwie abzufragen?
Vorher ging ja komischerweise alles...
Also liegt es an der neuen Software der Anlage?

Bin in der Materie nicht so weit drin, bin aber trotzdem bereit zu testen und zu unterstützen wo ich kann.

**Comment by TA2k** [comment]
Nein geht nicht nur mit dem skript
https://forum.iobroker.net/topic/47225/bwt-weichwasseranlage-auslesen/4?_=1648149935405

**Comment by mbhomie007** [comment]
Vielen Dank für deine Rückmeldung.
Sehr schade...

**Comment by mbhomie007** [comment]
> Nein geht nicht nur mit dem skript
> https://forum.iobroker.net/topic/47225/bwt-weichwasseranlage-auslesen/4?_=1648149935405

Hallo @TA2k

Hättest du Kapazität das Skript in den Adapter zu integrieren, sodass die lokale Abfrage per IP-Adresse wieder möglich ist?

**Comment by TA2k** [comment]
Eher nicht das ist sehr speziell mit OCR Erkennung ohne eignes Gerät ist das schwierig

**Comment by mbhomie007** [comment]
Mit neuer V2.02xx Firmware nun per API abrufbar.
