### ISSUE TITLE
Abfrage der Säulendetails

### ISSUE THREAD

**Issue by rrrrralf** [TA2k/ioBroker.bwt#9]
Zur Abfrage der Säulendetails (Restkapazität, Status, Laufzeit der Regeneration, Regenerationsschritt, Absaugung der Sole) können die Infos aus "/info/updateDetails2" verwendet werden.

Diese Details können z.B. bei Ein-Säulen-Anlagen verwendet werden um manuell die Regeneration zu starten.
Somit kommt man nicht in die Situation das die Restkapazität erschöpft ist und nur "hartes" Wasser zur Verfügung steht.

Zum Auslesen der Details habe ich bei mir folgendes in der "main.js" ab Zeile 245 eingetragen.
(Ich bin kein Entwickler/Programmierer und es war ein Versuch auf gut Glück.)

            {
                path: "updateDetails2",
                url: "https://" + this.config.localIp + "/info/updateDetails2",
            },

Hierbei ergeben sich dann diese zusätzliche Objekte.

![bwt](https://user-images.githubusercontent.com/105041990/167093323-5956e1ea-8241-48a6-b196-507a7a7e245c.png)

durchfluss = aktueller Durchfluss (l/h)
menge = Solezähler - Zuletzt abgesaugte Menge (ml)
restkap1 = Restkapazität Säule 1 (Angabe in Liter)
restkap2 = Restkapazität Säule 2 (Angabe in Liter)
restlz1 = Restlaufzeit der Regeneration Säule 1 (Angabe in Minuten)
restlz2 = Restlaufzeit der Regeneration Säule 2 (Angabe in Minuten)
Saugrate = Solezähler - Aktuelle Saugrate (ml/s)
step1 = Regenerationsschritt Säule 1 (Betrieb, Rückspülen, Gesalzen, Verdängen, ...)
step2 = Regenerationsschritt Säule 2 (Betrieb, Rückspülen, Gesalzen, Verdängen, ...)

Evtl. wäre dies auch für andere Nutzer hilfreich und könnte mit in die nächste Version einfließen.

**Comment by TA2k** [comment]
Danke für den hinweis habe es mal in die github version eingefügt
